name: Run Flink Jira Bot Twice Daily

on:
  schedule:
      - cron: 33 10,22 * * *
jobs:
  run:
    env:
      JIRA_PASSWORD: ${{ secrets.FLINK_JIRA_BOT_PASSWORD }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Jira Bot
        run: |
          python flink_jira_bot.py